trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - src/EFCore.PG.JToken/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true
    
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: 'src/EFCore.PG.JToken'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/EFCore.PG.JToken/EFCore.PG.JToken.csproj'
    includesymbols: true
    includesource: true
    buildProperties: 'VersionSuffix="$(Build.BuildNumber)"'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/EFCore.PG.JToken/EFCore.PG.JToken.csproj'
    includesymbols: true
    includesource: true
    versioningScheme: 'off'
  condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/'))

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'myget'